LOCUS       RPE65_CYNPY              533 aa            linear   VRT 07-JAN-2015
DEFINITION  RecName: Full=Retinoid isomerohydrolase; AltName:
            Full=All-trans-retinyl-palmitate hydrolase; AltName: Full=Retinal
            pigment epithelium-specific 65 kDa protein; AltName: Full=Retinol
            isomerase.
ACCESSION   Q8AXN9
VERSION     Q8AXN9.3  GI:48474842
DBSOURCE    UniProtKB: locus RPE65_CYNPY, accession Q8AXN9;
            class: standard.
            created: Oct 10, 2003.
            sequence updated: Jan 23, 2007.
            annotation updated: Jan 7, 2015.
            xrefs: AB095018.1, BAC41351.1
            xrefs (non-sequence databases): ProteinModelPortal:Q8AXN9,
            HOVERGEN:HBG050679, GO:0016020, GO:0052885, GO:0052884, GO:0016853,
            GO:0046872, GO:0050896, GO:0007601, InterPro:IPR004294,
            PANTHER:PTHR10543, Pfam:PF03055
KEYWORDS    Acetylation; Hydrolase; Iron; Isomerase; Lipoprotein; Membrane;
            Metal-binding; Palmitate; Phosphoprotein; Sensory transduction;
            Vision.
SOURCE      Cynops pyrrhogaster (Japanese firebelly newt)
  ORGANISM  Cynops pyrrhogaster
            Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi;
            Amphibia; Batrachia; Caudata; Salamandroidea; Salamandridae;
            Pleurodelinae; Cynops.
REFERENCE   1  (residues 1 to 533)
  AUTHORS   Nakamura,K., Kikuchi,Y., Susaki,K., Chiba,C. and Saito,T.
  TITLE     Direct Submission
  JOURNAL   Submitted (??-OCT-2002)
  REMARK    NUCLEOTIDE SEQUENCE [MRNA].
COMMENT     [FUNCTION] Plays important roles in the production of 11-cis
            retinal and in visual pigment regeneration. The soluble form binds
            vitamin A (all-trans-retinol), making it available for LRAT
            processing to all-trans-retinyl ester. The membrane form,
            palmitoylated by LRAT, binds all-trans-retinyl esters, making them
            available for IMH (isomerohydrolase) processing to all-cis-retinol.
            The soluble form is regenerated by transferring its palmitoyl
            groups onto 11-cis-retinol, a reaction catalyzed by LRAT. The
            enzymatic activity is linearly dependent of the expression levels
            and membrane association (By similarity). {ECO:0000250}.
            [CATALYTIC ACTIVITY] An all-trans-retinyl ester + H(2)O =
            11-cis-retinol + a fatty acid.
            [COFACTOR] Name=Fe(2+); Xref=ChEBI:CHEBI:29033;
            Evidence={ECO:0000250}; Note=Binds 1 Fe(2+) ion per subunit.
            {ECO:0000250}.
            [SUBCELLULAR LOCATION] Membrane {ECO:0000250}; Lipid-anchor
            {ECO:0000250}.
            [TISSUE SPECIFICITY] Retinal pigment epithelium specific.
            [PTM] Palmitoylation by LRAT regulates ligand binding specificity;
            the palmitoylated form (membrane form) specifically binds
            all-trans-retinyl-palmitate, while the soluble unpalmitoylated form
            binds all-trans-retinol (vitamin A). {ECO:0000250}.
            [SIMILARITY] Belongs to the carotenoid oxygenase family.
            {ECO:0000305}.
FEATURES             Location/Qualifiers
     source          1..533
                     /organism="Cynops pyrrhogaster"
                     /db_xref="taxon:8330"
     gene            1..533
                     /gene="RPE65"
     Protein         1..533
                     /gene="RPE65"
                     /product="Retinoid isomerohydrolase"
                     /EC_number="3.1.1.64"
                     /note="All-trans-retinyl-palmitate hydrolase; Retinal
                     pigment epithelium-specific 65 kDa protein; Retinol
                     isomerase"
                     /UniProtKB_evidence="Evidence at transcript level"
     Region          2..533
                     /gene="RPE65"
                     /region_name="Mature chain"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="Retinoid isomerohydrolase. /FTId=PRO_0000143948."
     Site            2
                     /gene="RPE65"
                     /site_type="modified"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="N-acetylserine. {ECO:0000250}."
     Region          20..533
                     /gene="RPE65"
                     /region_name="RPE65"
                     /note="Retinal pigment epithelial membrane protein;
                     pfam03055"
                     /db_xref="CDD:251697"
     Site            112
                     /gene="RPE65"
                     /site_type="lipid-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="S-palmitoyl cysteine; in membrane form.
                     {ECO:0000250}."
     Site            180
                     /gene="RPE65"
                     /site_type="metal-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="Iron; catalytic. {ECO:0000250}."
     Site            231
                     /gene="RPE65"
                     /site_type="lipid-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="S-palmitoyl cysteine; in membrane form.
                     {ECO:0000250}."
     Site            241
                     /gene="RPE65"
                     /site_type="metal-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="Iron; catalytic. {ECO:0000250}."
     Site            313
                     /gene="RPE65"
                     /site_type="metal-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="Iron; catalytic. {ECO:0000250}."
     Site            329
                     /gene="RPE65"
                     /site_type="lipid-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="S-palmitoyl cysteine; in membrane form.
                     {ECO:0000250}."
     Site            330
                     /gene="RPE65"
                     /site_type="lipid-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="S-palmitoyl cysteine; in membrane form.
                     {ECO:0000250}."
     Site            527
                     /gene="RPE65"
                     /site_type="metal-binding"
                     /experiment="experimental evidence, no additional details
                     recorded"
                     /note="Iron; catalytic. {ECO:0000250}."
ORIGIN      
        1 msskvehpag gykklfetve elaspitahv tgripvwltg sllrcgpglf evgseqfyhl
       61 fdgqallhkf dfkeghvtyh rrfirtdtyv ramtekrivi tefgtfafpd pcknifsrfl
      121 syfqglevtd ntlvnvypvg edyyactetn yitkvnpetl etikkvdlcn yvsingvtah
      181 pliendgtvy nigncfgkhf sfaynivkip plqedkedpi nkakvvvqfp cserfkpsyv
      241 hsfgltpnyi vfveqpvkin lfkflsswsi wganymdcfe shetmgvwmh vaekltgeyl
      301 nikyrtsafn lfhhintyed hgflivdlcc wkgfefiyny lylanmrenw eevkrnaeka
      361 pqpevrryvl pldihkvdtg knlvnlpytt atailrsdet iwlepevlfs gprlafefpq
      421 inykkfggkd ytfayglgln hfvpdrlskl nvktkeiwvw qepdsypsep ifvsqpdame
      481 eddgvvlsvi vnpgpgqkpa fllilnakdm seiaraevdi nipvtfhgmy kka
//

